[package]
name = "freezer"
version = "0.1.0"
edition = "2024"

[dependencies]
lettre = "0.11.18"
reqwest = { version = "0.12.23", features = ["blocking"] }
rss = { version = "2.0.12", features = ["validation"] }
